name: Build_and_test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_unit_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - name: SoftUni username - niki.evgeniev
      run: echo 'niki.evgeniev'
    - name: Install dep.
      run: npm install
    - name: Run unit tests
      run: npm run test:unit
  build_and_UI_Test:
    needs: build_and_unit_test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.X
        cache: 'npm'
    - name: Install dep.
      run: npm install
    - name: Install playwright
      run: npx playwright install
    - name: Npm Run App in background
      run: npm run start &
    - name: Run UI tests
      run: npm run test:ui
